<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Taser | Register',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'francisco.maidana@bingopilar.com.ar',
		'to' => 'francisco.maidana@bingopilar.com.ar'
	),
	'fields' => array(
		'custom_U1982' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'NAME',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'NAME\' es obligatorio.'
			)
		),
		'custom_U1948' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'ADDRESS',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'ADDRESS\' es obligatorio.'
			)
		),
		'custom_U1954' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'City\' es obligatorio.'
			)
		),
		'custom_U1962' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'State\' es obligatorio.'
			)
		),
		'custom_U1996' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Zip Code',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Zip Code\' es obligatorio.'
			)
		),
		'custom_U1987' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Country\' es obligatorio.'
			)
		),
		'custom_U1944' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'PHONE NUMBER',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'PHONE NUMBER\' es obligatorio.'
			)
		),
		'custom_U1992' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Street address Line 2',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Street address Line 2\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 9,
			'type' => 'email',
			'label' => 'INSTAGRAM USERNAME',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'INSTAGRAM USERNAME\' es obligatorio.',
				'format' => 'El campo \'INSTAGRAM USERNAME\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U1978' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'PAYPAL ACCOUNT EMAIL',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'PAYPAL ACCOUNT EMAIL\' es obligatorio.'
			)
		),
		'custom_U1966' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'TEASER RULES',
			'required' => true,
			'optionItems' => array(
				'I have read,understood, and accepted the rules of Teaser',
				'I have read, understood, and accepted the PRIVACY POLICY agreement',
				'18 YEARS OR OLDER

     I consent that am of age (18 year or     older) to use this plataform'
			),
			'errors' => array(
				'required' => 'El campo \'TEASER RULES\' es obligatorio.',
				'format' => 'El campo \'TEASER RULES\' contiene un valor no válido.'
			)
		)
	)
);

process_form($form);
?>
